<a href="https://colab.research.google.com/github/12004281-INT102/PYTHON-PROGRAMMING/blob/main/array_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Slicing of 2d array

In [1]:
import numpy as np

In [ ]:
A=np.arange(27).reshape(3,9)
print(A)

In [6]:
#array_name[start_row_index:end_row_index , start_col_index:end_col_index] # end always n-1
print(A[1:3,6:9])

[[15 16]
 [24 25]]


In [ ]:
#array operations(mathematicals ) on both 1D and 2D

In [ ]:
A=np.array([20,37,53,62,97,83,26,44,29,17,81,65])
print(A)
B=A + 10
print(B)

In [47]:
C = B-6
print(C)
D= C* 4
print(D)
sqr=A ** 2
print(sqr)

[ 24  41  57  66 101  87  30  48  33  21  85  69]
[ 96 164 228 264 404 348 120 192 132  84 340 276]
[ 400 1369 2809 3844 9409 6889  676 1936  841  289 6561 4225]


In [21]:
A1=np.array([1,2,3,4,5])
A2=np.array([6,7,8,9,10])
A3=A1+A2
print(A3)
A4=np.add(A1,A2)
print(A4)
A5=A1-A2
print(A5)
A6=np.subtract(A1,A2)
print(A6)
A7=np.multiply(A4,A6) # or A7= A4 * A6
print(A7)
A8=np.divide(A7,A3) # or A7/A3 for not float A7 // A3
print(A8)

[ 7  9 11 13 15]
[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[-5 -5 -5 -5 -5]
[-35 -45 -55 -65 -75]
[-5. -5. -5. -5. -5.]


In [ ]:
T=np.array([10,20,30,40,50,60,70,80,90,100])
print(T.max())
print(T.min())
print(T.sum())
print(T.mean())
print(int(T.mean()))
print(T.std())
print(T.var())
print(T.prod())

In [ ]:
S=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(S)
print(S.max())
print(S.max(axis=1)) #max in row wise
print(S.max(axis=0)) # max in column wise
print(S.sum())
print(S.sum(axis=1))
print(S.sum(axis=0))
print(S.prod())
print(S.prod(axis=1))
print(S.prod(axis=0))
print(S.diagonal())
print(S.transpose())

In [ ]:
M=np.arange(1,10).reshape(3,3)
print(M)
N=M+S
print(N)
N=np.add(M,S)
print(N)

In [ ]:
# in 2D array two type of multiplication 
#1 element wise ( * )
#2 matrix wise( @ or dot)

In [ ]:
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
b=np.array([[5,6,7],[8,9,4],[1,2,3]])
c= a* b
print(c)
c= a @ b # or c=a.dot(b)
print(c)

In [ ]:
A=np.array([ [96 ,164 ,228] ,[264 ,404 ,348] ,[120 ,192 ,132] , [84 ,340 ,276]])
print(A)
B=np.sort(A,axis=0)
print(B)

In [ ]:
A=np.array([ [96 ,164 ,228] ,[264 ,404 ,348] ,[120 ,192 ,132] , [84 ,340 ,276]])
#print min without function
print(A)
min=A[0][0]
for x in range(4):
  for y in range(3):
    if(min>A[x][y]):
      min=A[x][y]
print('Minimum value',min)

In [ ]:
#copying and viewing array
# 2 types- shallow-copy() and deep-view() 
A=np.array([1,2,3,4,5,6,7,8,9,10])
print(A)
B=A.copy()
print(B) #shallow copy means a change in A wont affect B and vise versa
B[0]=20
print(B)
C=A.view()
print(C) #deep copy means a change in A made, the change will be there in C
A[0]=19
print(A)
print(C)

In [ ]:
#count the total occurance of given elements
#search the given elements from 1D or 2D
#print the max value from 1D and 2D 

In [63]:
#create a 3D array
#its an array of 2D arrays
A=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]],[[21,22,23],[24,25,26],[27,28,29]]])
print(A)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


In [ ]:
print(A[1][1][1])
#sliciing
#array_name[start_2D_index:end_2d_array_index,start_row_index:end_row_index,start_col_index:end_col_index]
print(A[1:2,1:3,0:2])
print(A.shape)
print(A.size)


In [ ]:
A=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]],[[21,22,23],[24,25,26],[27,28,29]]])
A.shape=(9,3)
print(A)

In [ ]:
#flatten() converts any nD array to 1D array
A=np.arange(54).reshape(2,3,9)
print(A)
print(A.flatten())